//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards.Core.src.Services.Storage.LocalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlashCard
    {
        public int Id { get; set; }
        public string Term { get; set; }
        public string Definition { get; set; }
        public int FlashCardSetId { get; set; }
        public int TimeStudied { get; set; }
        public int ErrorsMade { get; set; }
    
        public virtual FlashCardSet FlashCardSet { get; set; }
    }
}
