//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards.Core.src.Services.Storage.LocalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlashCardSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlashCardSet()
        {
            this.FlashCards = new HashSet<FlashCard>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TermLanguageCode { get; set; }
        public string DefinitionLanguageCode { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
        public string Owner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlashCard> FlashCards { get; set; }
    }
}
