//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards.Core.src.Services.Storage.LocalDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalStorageDBContext : DbContext
    {
        public LocalStorageDBContext()
            : base("name=LocalStorageDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FlashCard> FlashCards { get; set; }
        public virtual DbSet<FlashCardSet> FlashCardSets { get; set; }
    }
}
